name: Deploy & Log to S3

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    outputs:
      deploy-status: ${{ steps.deploy-status.outputs.deploy-status }}
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Construir el proyecto
        run: npm run build

      - name: Desplegar en Vercel
        id: vercel-deploy
        run: |
          npm install -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
        continue-on-error: true

      - name: Verificar resultado del despliegue
        id: deploy-status
        shell: bash
        # https://docs.github.com/es/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs#ejemplo-definir-salidas-para-un-job
        run: |
          if [[ $? -eq 0 ]]; then
            echo "deploy-status=EXITO || Despliegue exitoso en Vercel" >> "$GITHUB_OUTPUT"
          else
            echo "deploy-status=ERROR || El despliegue en Vercel falló" >> "$GITHUB_OUTPUT"
          fi

  upload-result-s3:
    needs: deploy-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Verificar variables de entorno
        shell: bash
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}"

      - name: Usar action personalizada para subir log a S3
        uses: JosthinAyonC/upload-log-s3@v1.0
        with:
          log-text: |
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Mensaje: ${{ github.event.head_commit.message }}
            Status deployment: ${{ needs.deploy-frontend.outputs.deploy-status }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucket-name: ${{ secrets.AWS_BUCKET_NAME }}
